#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "core/geometry/lattice.hpp"
#include "core/math/particle_data.hpp"

namespace aleator::engines {

/// Porous-material geometry descriptors, computed from the periodic radical
/// Voronoi network of the framework (`voronoi_network.hpp`, itself built on
/// Voro++ — see that header and CLAUDE.md section 0 for why). Validated
/// against Zeo++'s own output for LTA, MFI, FAU (CLAUDE.md #4) — see
/// `tests/validation/test_pore_geometry.cc` for the achieved tolerance and
/// full provenance of the reference numbers (generated by running the real
/// Zeo++ 0.4.7 tool on the same real IZA structures, not transcribed from
/// a paper table, so the comparison is exactly reproducible).
struct PoreGeometry {
    /// Largest cavity diameter: 2x the largest free-sphere radius found
    /// anywhere in the void space (exact — a global maximum over Voronoi
    /// network node radii, not Monte Carlo sampled).
    double largestCavityDiameterAngstrom;
    /// Pore limiting diameter: 2x the largest probe radius that can still
    /// percolate through the periodic structure (exact — a graph
    /// percolation-threshold computation over the Voronoi network, not
    /// Monte Carlo sampled). Zero if the structure has no percolating void
    /// space at all (e.g. a fully dense or fully pocketed structure).
    double poreLimitingDiameterAngstrom;
    /// Surface area (accessible to a probe of `probeRadiusAngstrom`) of the
    /// part of the atom-surface manifold that belongs to the percolating
    /// (accessible) network, per unit cell. Monte Carlo estimated (matching
    /// Zeo++'s own methodology), so this carries real sampling noise — see
    /// `asaSamplesPerAtom` below.
    double accessibleSurfaceAreaAngstromSq;
    /// Surface area belonging to non-percolating pockets (accessible
    /// locally to the probe but disconnected from the percolating
    /// network) — Zeo++ calls this "NASA". Zero for a structure with no
    /// blocked pockets.
    double inaccessibleSurfaceAreaAngstromSq;
    /// Void volume belonging to the percolating (accessible) network, per
    /// unit cell. Monte Carlo estimated.
    double accessibleVolumeAngstromCubed;
    /// Void volume belonging to non-percolating pockets — Zeo++'s "NAV".
    /// Zero for a structure with no blocked pockets. Together with
    /// `accessibleVolumeAngstromCubed` and the atoms' own volume, this is
    /// part of `totalVolumeAngstromCubed`.
    double inaccessibleVolumeAngstromCubed;
    /// The unit cell volume (a convenience — `core::Lattice::volume()`
    /// applied to whatever lattice was passed in, for computing volume
    /// fractions without the caller needing to keep the lattice around).
    double totalVolumeAngstromCubed;
};

/// Monte Carlo sampling parameters for the surface-area/volume estimates
/// (CLAUDE.md's "probe-radius parameterized" requirement) — LCD/PLD need
/// none of this, since they're exact graph computations.
struct PoreAnalysisOptions {
    double probeRadiusAngstrom = 1.86; // N2, the literature-standard default (see README)
    std::size_t asaSamplesPerAtom = 2000;
    std::size_t volumeSamplesTotal = 50'000;
    /// Seed for the Monte Carlo sampling — deterministic (CLAUDE.md
    /// invariant #5), same seed/input always gives the same ASA/AV.
    std::uint64_t sampleSeed = 0;
};

/// `perSpeciesRadiusAngstrom[framework.species[i]]` is atom i's radius —
/// same per-species-indexed convention as `forcefield::LennardJones`'s
/// `perSpecies` parameter table. Throws std::invalid_argument if any
/// species index is out of range, or if `framework` is empty.
[[nodiscard]] PoreGeometry analyzePoreGeometry(const core::ParticleData& framework,
                                                const core::Lattice& lattice,
                                                const std::vector<double>& perSpeciesRadiusAngstrom,
                                                const PoreAnalysisOptions& options = {});

/// The van der Waals radius (Å) Zeo++ uses by default for `element` (its
/// own default radius table, traced to Zeo++'s `networkinfo.cc`,
/// `initializeRadTable()`, comment "Parameters taken from CCDC tables") —
/// exposed so a caller (or a test comparing against real Zeo++ output) can
/// reproduce Zeo++'s numbers exactly without needing its own separate
/// radius source. Not a general-purpose periodic table: only the elements
/// this codebase's example/test frameworks actually use. Throws
/// std::invalid_argument for an unlisted element.
[[nodiscard]] double zeoPlusPlusDefaultRadiusAngstrom(const std::string& element);

} // namespace aleator::engines
